PROC SQL;

CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2009(PRODUCT_ID);
CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2010(PRODUCT_ID);
CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2011(PRODUCT_ID);
CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2012(PRODUCT_ID);
CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2013(PRODUCT_ID);
CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2014(PRODUCT_ID);
CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2015(PRODUCT_ID);
CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2016(PRODUCT_ID);
CREATE INDEX PRODUCT_ID ON Rxdata.Rxfact_2017(PRODUCT_ID);

CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2009(PROVIDER_ID);
CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2010(PROVIDER_ID);
CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2011(PROVIDER_ID);
CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2012(PROVIDER_ID);
CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2013(PROVIDER_ID);
CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2014(PROVIDER_ID);
CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2015(PROVIDER_ID);
CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2016(PROVIDER_ID);
CREATE INDEX PROVIDER_ID ON Rxdata.Rxfact_2017(PROVIDER_ID);

CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2009(PATIENT_ID);
CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2010(PATIENT_ID);
CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2011(PATIENT_ID);
CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2012(PATIENT_ID);
CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2013(PATIENT_ID);
CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2014(PATIENT_ID);
CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2015(PATIENT_ID);
CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2016(PATIENT_ID);
CREATE INDEX PATIENT_ID ON Rxdata.Rxfact_2017(PATIENT_ID);


CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2009(PRODUCT_ID, PATIENT_ID);
CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2010(PRODUCT_ID, PATIENT_ID);
CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2011(PRODUCT_ID, PATIENT_ID);
CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2012(PRODUCT_ID, PATIENT_ID);
CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2013(PRODUCT_ID, PATIENT_ID);
CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2014(PRODUCT_ID, PATIENT_ID);
CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2015(PRODUCT_ID, PATIENT_ID);
CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2016(PRODUCT_ID, PATIENT_ID);
CREATE INDEX PRODUCT_TO_PATIENT ON Rxdata.Rxfact_2017(PRODUCT_ID, PATIENT_ID);

CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2009(PRODUCT_ID, PROVIDER_ID);
CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2010(PRODUCT_ID, PROVIDER_ID);
CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2011(PRODUCT_ID, PROVIDER_ID);
CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2012(PRODUCT_ID, PROVIDER_ID);
CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2013(PRODUCT_ID, PROVIDER_ID);
CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2014(PRODUCT_ID, PROVIDER_ID);
CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2015(PRODUCT_ID, PROVIDER_ID);
CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2016(PRODUCT_ID, PROVIDER_ID);
CREATE INDEX PRODUCT_TO_PROVIDER ON Rxdata.Rxfact_2017(PRODUCT_ID, PROVIDER_ID);
